// Shared products data - use this for both API and server components
export const products = [
  {
    _id: "1",
    name: "Pro Badminton Racket",
    description: "High quality badminton racket for professional players",
    price: 150000,
    stock: 10,
    category: {
      _id: "1",
      name: "Badminton",
      description: "Badminton equipment and gear",
      imageUrl: "/images/categories/category-badminton.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-1.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Basketball Official Size",
    description: "Official size basketball for professional games",
    price: 250000,
    stock: 15,
    category: {
      _id: "2",
      name: "Basketball",
      description: "Basketball equipment and gear",
      imageUrl: "/images/categories/category-basketball.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-2.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "Running Shoes Pro",
    description: "Lightweight running shoes for marathon runners",
    price: 450000,
    stock: 8,
    category: {
      _id: "4",
      name: "Running",
      description: "Running equipment and gear",
      imageUrl: "/images/categories/category-running.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-3.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "Swimming Goggles",
    description: "Professional swimming goggles with anti-fog",
    price: 85000,
    stock: 20,
    category: {
      _id: "5",
      name: "Swimming",
      description: "Swimming equipment and gear",
      imageUrl: "/images/categories/category-swimming.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-4.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    name: "Tennis Racket Elite",
    description: "Elite tennis racket for competitive play",
    price: 350000,
    stock: 12,
    category: {
      _id: "6",
      name: "Tennis",
      description: "Tennis equipment and gear",
      imageUrl: "/images/categories/category-tennis.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-5.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    name: "Football Cleats",
    description: "Professional football cleats for turf",
    price: 280000,
    stock: 18,
    category: {
      _id: "3",
      name: "Football",
      description: "Football equipment and gear",
      imageUrl: "/images/categories/category-football.png",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    imageUrl: "/images/products/product-6.png",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export function getProducts() {
  return products;
}

